import Head from "next/head";
import Image from "next/image";
import { UserFactory } from "nightfall-sdk";
import { config } from "../lib/config";
import styles from "../styles/Home.module.css";

export default function Home() {
  const onClick = async () => {
    let user;
    try {
      // # 1 Create an instance of User
      user = await UserFactory.create(config);

      // # 2 Check Nightfall balances
      const balances = await user.checkNightfallBalances();
      console.log("Balances", balances);
    } catch (error) {
      console.log(error);
      process.exit(1);
    } finally {
      user.close();
      console.log("Bye bye");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={onClick}>deposit</button>
    </div>
  );
}
