import Head from "next/head";
import Image from "next/image";
import { UserFactory } from "nightfall-sdk";
import { config } from "../lib/config";
import styles from "../styles/Home.module.css";

export default function Home() {
  const onClick = async () => {
    let user;
    try {
      // # 1 Create an instance of User
      user = await UserFactory.create(config);

      // # 2 Check Nightfall balances
      const balances = await user.checkNightfallBalances();
      console.log("Balances", balances);
    } catch (error) {
      console.log(error);
      process.exit(1);
    } finally {
      user.close();
      console.log("Bye bye");
    }
  };
  const onClick2 = async () => {
    let user;
    try {
      // # 1 Create an instance of User (mnemonic is optional)
      user = await UserFactory.create(config);

      // # 2 [OPTIONAL] If you did not pass a mnemonic, you can retrieve it
      const mnemonic = user.getNightfallMnemonic();
      console.log(mnemonic, "mnemonic");

      // # 3 [OPTIONAL] You can check API Client, blockchain ws connection
      const status = await user.checkStatus();
      console.log("API Client, blockchain ws statuses", status);

      // # 4 Make deposit
      const tokenContractAddress = config.tokenContractAddress;
      const tokenErcStandard = "ERC20";
      const value = "0.0001";
      const txReceipts = await user.makeDeposit({
        tokenContractAddress,
        tokenErcStandard,
        value,
      });
      console.log("Transaction receipts", txReceipts);

      // # 5 [OPTIONAL] You can check the transaction hash
      console.log("Nightfall deposit tx hashes", user.nightfallDepositTxHashes);

      // # 6 [OPTIONAL] You can check deposits that are not yet in Nightfall
      const pendingDeposits = await user.checkPendingDeposits();
      console.log("Pending balances", pendingDeposits);
    } catch (error) {
      console.log(error);
      process.exit(1);
    } finally {
      user.close();
      console.log("Bye bye");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={onClick}>deposit</button>
      <button onClick={onClick2}>create</button>
    </div>
  );
}
